FORMAT: 1A

# nuseats

# Group Canteens

## Canteen Collection [/canteens]

### Retrieve all Canteens [GET]

+ Request JSON

    + Headers
    
            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "canteens": [
                    {
                        "id": 1,
                        "name": "Techno Edge",
                        "latitude": 51.503362,
                        "longtitude": -0.1276250,
                    }
                ]
            }

## Store Collection [/canteens/id]

### Retrieve all Stores belonging to a Canteen [GET]

+ Request JSON

    + Headers
    
            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "stores": [
                    {
                        "id": 1,
                        "name": "Ah Huat's Chicken Rice",
                        "stars": 3.5,
                        "image": {
                            "user_id": 1,
                            "url": "/image.png"
                        }
                    }
                ]
            }

# Group Stores

## Store [/stores/{id}]

### Retrieve a Store [GET]

+ Request JSON

    + Headers
    
            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body
        
            {
                "name": "Ah Huat's Chicken Rice",
                "stars": 3.5,
                "images": [
                    {
                        "user_id": 1,
                        "url": "/image.png"
                    }
                ],
            }

## Review Collection [/stores/reviews/{id}]

### Retrieve a Store [GET]

+ Request JSON

    + Headers
    
            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "reviews": [
                    "user_id": 1,
                    "review": "This store is awesome!",
                    "stars": 4
                ]
            }
