FORMAT: 1A

# nuseats

# Group Login

## Authentication [/authentication/login]

### (DONE) Get JWT from FB User Access Token [POST]

+ Request JSON

    + Headers

            Content-Type: application/json

    + Body

            {
                "accessToken": "EAABzvgZBDLz4BAM617uSUddJJ2hWrnxSQcExGQF85bUvGdnbP6aP4Ey"
            }

+ Response 200 (application/json)

    + Body

            {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cC",
                "facebookToken": "EAABzvgZBDLz4BAM617uSUddJJ2hWrnxSQcExGQF85bUvGdnbP6aP4Ey"
            }

+ Response 401 (application/json)

    + Body

            {
                "statusCode": 401,
                "error": "Unauthorized",
                "message": "Invalid access token."
            }

# Group Canteens

## Canteen Collection [/canteens]

### (DONE) Get all Canteens [GET]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "canteens": [
                    {
                        "id": 3,
                        "name": "PGP E-Canteen",
                        "latitude": 1.2907629,
                        "longitude": 103.78228426,
                        "createdAt": "2017-08-23T16:00:00.000Z",
                        "updatedAt": "2017-08-23T16:00:00.000Z",
                        "crowdValue": 0.1497255
                    }
                ]
            }

+ Response 200 (application/json)

    + Body

            {
                "canteens": []
            }


+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }

# Group Stalls

## Stall Collection [/stalls]

## (DONE) Get all stalls [GET]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "stalls": [
                    {
                        "id": 1,
                        "name": "Dickson's North Indian Halal Food",
                        "createdAt": "2017-08-23T16:00:00.000Z",
                        "updatedAt": "2017-08-23T16:00:00.000Z",
                        "canteenId": 1,
                        "averageRating": 2.75
                        "image": {
                            "id": 1,
                            "url": "/images/image.jpeg",
                            "mimetype": "image/jpeg",
                            "likedUsers": [3, 4, 45, 47, 52],
                            "userId": 5,
                            "stallId": 1,
                            "createdAt": "2017-08-23T16:00:00.000Z",
                            "updatedAt": "2017-08-23T16:00:00.000Z"
                        }
                    }
                ]
            }

+ Response 200 (application/json)

    + Body

            {
                "stalls": []
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }

## Stall [/stalls/{id}]

### (DONE) Get a Stall [GET]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "stall": {
                    "id": 1,
                    "name": "Dickson's North Indian Halal Food",
                    "createdAt": "2017-08-23T16:00:00.000Z",
                    "updatedAt": "2017-08-23T16:00:00.000Z",
                    "canteenId": 1,
                    "averageRating": 2.75
                }
            }

+ Response 404 (application/json)

    + Body
            {
                "statusCode": 404,
                "error": "Not Found",
                "message": "Record not found."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }

## Ratings Collection [/stalls/{id}/ratings]

### (DONE) Get all Ratings of a Stall [GET]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "ratings": [
                    {
                        "id": 2,
                        "value": 2,
                        "userId": "8775234563",
                        "createdAt": "2017-08-23T16:00:00.000Z",
                        "updatedAt": "2017-08-23T16:00:00.000Z",
                        "stallId": 1
                    }
                ]
            }

+ Response 200 (application/json)

    + Body

            {
                "ratings": []
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }

### (NOT DONE) Add user Ratings to a Stall [POST]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

    + Body

            {
                "value": 3
            }

+ Response 200 (application/json)

## Images Collection [/stalls/{id}/images]

### (NOT DONE) Get all Images of a Stall [GET]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "images": [
                    {
                        "id": 1,
                        "url": "/images/image.jpeg",
                        "mimetype": "image/jpeg",
                        "likedUsers": [3, 4, 45, 47, 52],
                        "userId": 5,
                        "stallId": 1,
                        "createdAt": "2017-08-23T16:00:00.000Z",
                        "updatedAt": "2017-08-23T16:00:00.000Z"
                    }
                ]
            }

# Group Users

## Appointment Collection [/users/{id}/appointments]

### (DONE) Get all appointments of a User [GET]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "appointments": [
                    {
                        "id": 1,
                        "attendees": ["336567", "787686", "39893", "579879"],
                        "canteenId": 1,
                        "userId": "23241",
                        "startTime": "140920171300",
                        "endTime": "140920171400",
                        "createdAt": "2017-08-23T16:00:00.000Z",
                        "updatedAt": "2017-08-23T16:00:00.000Z",
                    }
                ]
            }

+ Response 200 (application/json)

    + Body

            {
                "appointments": []
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }

## Image Collection [/users/{id}/images]

### (NOT DONE) Get all images uploaded by a User [GET]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "images": [
                    {
                        "id": 1,
                        "url": "/images/image.jpeg",
                        "mimetype": "image/jpeg",
                        "likedUsers": [3, 4, 45, 47, 52],
                        "userId": 5,
                        "stallId": 1,
                        "createdAt": "2017-08-23T16:00:00.000Z",
                        "updatedAt": "2017-08-23T16:00:00.000Z"
                    }
                ]
            }

# Group Images

## Image Upload [/images]

### (NOT DONE) Upload an Image [POST]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: multipart/form-data

+ Response 201 (application/json)

## Image [/images/{id}]

### (NOT DONE) Like an Image [PATCH]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

### (NOT DONE) Delete an Image [DELETE]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

# Group Appointments

## Appointment Upload [/appointments]

### (DONE) Create an Appointment [POST]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Content-Type: application/json
            Accept: application/json

    + Body

            {
                "appointment": {
                    "canteenId": 3,
                    "startTime": "2017-08-22 16:00:00+00"",
                    "endTime": "2017-08-22 18:00:00+00""
                }
            }

+ Response 201 (application/json)

            {
                "appointment": {
                    "attendees": [],
                    "id": 4,
                    "userId": "1524106284336095",
                    "startTime": "2017-08-22T16:00:00.000Z",
                    "endTime": "2017-08-22T18:00:00.000Z",
                    "canteenId": 3,
                    "updatedAt": "2017-08-26T14:53:36.864Z",
                    "createdAt": "2017-08-26T14:53:36.864Z",
                    "deletedAt": null
                }
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Request breaks database constraints."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Sequelize validation failed."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }

## Appointment [/appointments/{id}]

### (DONE) Update an Appointment [PATCH]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Content-Type: application/json
            Accept: application/json

    + Body

            {
                "appointment": {
                    "canteenId": 7,
                    "startTime": "2017-08-22 16:00:00+00"",
                    "endTime": "2017-08-22 18:00:00+00""
                }
            }

+ Response 201 (application/json)

            {
                "appointment": {
                    "attendees": [],
                    "id": 4,
                    "userId": "1524106284336095",
                    "startTime": "2017-08-22T16:00:00.000Z",
                    "endTime": "2017-08-22T18:00:00.000Z",
                    "canteenId": 7,
                    "updatedAt": "2017-08-26T14:53:36.864Z",
                    "createdAt": "2017-08-26T14:53:36.864Z",
                    "deletedAt": null
                }
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Request breaks database constraints."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Sequelize validation failed."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }

### (DONE) Delete an Appointment [DELETE]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 204 (application/json)

+ Response 404 (application/json)

    + Body
            {
                "statusCode": 404,
                "error": "Not Found",
                "message": "Record not found."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Request breaks database constraints."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Sequelize validation failed."
            }

## Join an Appointment [/appointments/{id}/join]

### (DONE) Join an Appointment [POST]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "appointment": {
                    "attendees": ["4"],
                    "id": 4,
                    "userId": "1524106284336095",
                    "startTime": "2017-08-22T16:00:00.000Z",
                    "end_time": "2017-08-22T18:00:00.000Z",
                    "canteenId": 3,
                    "updatedAt": "2017-08-26T14:53:36.864Z",
                    "createdAt": "2017-08-26T14:53:36.864Z",
                    "deletedAt": null
                }
            }


+ Response 404 (application/json)

    + Body
            {
                "statusCode": 404,
                "error": "Not Found",
                "message": "Record not found."
            }

+ Response 403 (application/json)

    + Body
            {
                "statusCode": 403,
                "error": "Forbidden",
                "message": "Host cannot join his/her own appointment."
            }

+ Response 403 (application/json)

    + Body
            {
                "statusCode": 403,
                "error": "Forbidden",
                "message": "User has already joined appointment."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Request breaks database constraints."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Sequelize validation failed."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }

## Unjoin an Appointment [/appointments/{id}/unjoin]

### (DONE) Unjoin an Appointment [POST]

+ Request JSON

    + Headers

            Authorization: Bearer <jwt>
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "appointment": {
                    "attendees": [],
                    "id": 4,
                    "userId": "1524106284336095",
                    "startTime": "2017-08-22T16:00:00.000Z",
                    "end_time": "2017-08-22T18:00:00.000Z",
                    "canteenId": 3,
                    "updatedAt": "2017-08-26T14:53:36.864Z",
                    "createdAt": "2017-08-26T14:53:36.864Z",
                    "deletedAt": null
                }
            }


+ Response 404 (application/json)

    + Body
            {
                "statusCode": 404,
                "error": "Not Found",
                "message": "Record not found."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Problems connecting to database."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Request breaks database constraints."
            }

+ Response 400 (application/json)

    + Body
            {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Sequelize validation failed."
            }

+ Response 502 (application/json)

    + Body
            {
                "statusCode": 502,
                "error": "Bad Gateway",
                "message": "Unknown Sequelize error."
            }