export const RECEIVE_CANTEENS = 'RECEIVE_CANTEENS';
export const RECEIVE_STALLS = 'RECEIVE_STALLS';
export const OPEN_STALL_VIEW = 'OPEN_STALL_VIEW';
export const CLOSE_STALL_VIEW = 'CLOSE_STALL_VIEW';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const TOGGLE_MUSLIM_ONLY = 'TOGGLE_MUSLIM_ONLY';
