version: '3'

services:
  web:
    ports:
      - "3000:3000"
    volumes:
      - .:/nus-eats
      - /nus-eats/node_modules
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    command: sh -c "yarn && yarn start"

  postgres:
    image: postgres:9.6.4
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres:
